### ISSUE TITLE
How to use your code

### ISSUE THREAD

**Issue by jrsikken** [sparkfun/TMP006-Temp_Sensor_Breakout#6]
Hi, I would like to use your code but I'm confused because you have published three *.ino files. Can you please test you code on a recent Arduino IDE release, reduce the number off *.ino files to 1, and add a description where to place the I2C_16.h, TMP006.h files?

When compiling TMP006.ino I got below errors. 
TMP006:7: error: 'TMP006_CFG_8SAMPLE' was not declared in this scope
TMP006.ino: In function 'void setup()':
TMP006:14: error: 'config_TMP006' was not declared in this scope
TMP006.ino: In function 'void loop()':
TMP006:19: error: 'readObjTempC' was not declared in this scope
TMP006:23: error: 'readDieTempC' was not declared in this scope

**Comment by bboyho** [comment]
Hi,

I'm sorry for the delay in reply. I just noticed your comment when closing other issues. The example code for the TMP006 breakout board compiles without any issues in **Arduino IDE v1.6.5** and **v1.8.3**. The error that you are seeing usually indicates that the main sketch file (called _TMP006.ino_) is not able to understand the defined functions. You need to make sure that the _I2C_16.h_, _I2C_functions.ino_, _TMP006.h_, and the _TMP000_functions.ino_ are in the same folder as the main sketch file (i.e. the **C:\Users\...\TMP006-Temp_Sensor_Breakout-master\TMP006-Temp_Sensor_Breakout-master\Firmware\TMP006** directory). This is just another way of breaking up code [ [https://www.arduino.cc/en/Guide/Environment#toc8](https://www.arduino.cc/en/Guide/Environment#toc8)
 and [http://arduino.land/FAQ/content/7/43/en/breaking-a-sketch-into-multiple-files.html](http://arduino.land/FAQ/content/7/43/en/breaking-a-sketch-into-multiple-files.html) ] instead of using an Arduino library.
