### ISSUE TITLE
The Wire.requestFrom() should not have beginTransmission or endTransmission.

### ISSUE THREAD

**Issue by Koepel** [sparkfun/TMP006-Temp_Sensor_Breakout#9]
The Wire.beginTransmission() and Wire.endTransmission() should only be used when writing data to a I2C Slave. The Wire.requestFrom() is a complete I2C transaction on its own.

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. I was updating a few things in this repository and noticed your comment. I am not sure why engineer that was originally assigned to this board wrote the example code with the `Wire.beginTransmission()`:

[https://github.com/sparkfun/TMP006-Temp_Sensor_Breakout/blob/9643a7de4f4d517c49db694944d6255b0836633b/Firmware/TMP006/I2C_functions.ino#L9](https://github.com/sparkfun/TMP006-Temp_Sensor_Breakout/blob/9643a7de4f4d517c49db694944d6255b0836633b/Firmware/TMP006/I2C_functions.ino#L9) 

and `Wire.endTransmission()` :

https://github.com/sparkfun/TMP006-Temp_Sensor_Breakout/blob/9643a7de4f4d517c49db694944d6255b0836633b/Firmware/TMP006/I2C_functions.ino#L14](https://github.com/sparkfun/TMP006-Temp_Sensor_Breakout/blob/9643a7de4f4d517c49db694944d6255b0836633b/Firmware/TMP006/I2C_functions.ino#L14) 

around the `Wire.requestFrom()`. 

Looking at example code online using the `Wire.requestFrom()` [ like in pjrc's Teensyduino [ [https://www.pjrc.com/teensy/td_libs_Wire.html](https://www.pjrc.com/teensy/td_libs_Wire.html) ] it does not appear that people place those functions around the function. It sounds like it is redundant from your explanation. I do not have the physical board with me since it has been retired but the code does not seem to break. I will comment it out in this GitHub repo.

**Comment by bboyho** [comment]
I have commented the lines out. For anyone interested, here's some of @Koepel 's notes on the Arduino I2C library => [ [https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes) ].

Thanks @Koepel . 😃
